using DotNetGraphScanner.Graph;

namespace DotNetGraphScanner.Export;

/// <summary>
/// Generates a Cypher script suitable for loading into Neo4j.
/// Run with: cypher-shell -f graph.cypher  or paste into Neo4j Browser.
///
/// To connect via Neo4j Bolt driver instead, replace this class body with calls
/// to the official Neo4j.Driver NuGet package.
/// </summary>
public sealed class Neo4jCypherExporter : IGraphExporter
{
    public Task ExportAsync(GraphModel graph, string outputPath, CancellationToken ct = default)
    {
        using var sw = new System.IO.StreamWriter(outputPath, append: false, System.Text.Encoding.UTF8);

        sw.WriteLine("// Auto-generated by dotnet-graph-scanner");
        sw.WriteLine("// Import with: cypher-shell -f " + System.IO.Path.GetFileName(outputPath));
        sw.WriteLine();
        sw.WriteLine("// ── Constraints ──────────────────────────────────────────────────");
        sw.WriteLine("CREATE CONSTRAINT node_id IF NOT EXISTS FOR (n:Node) REQUIRE n.id IS UNIQUE;");
        sw.WriteLine();
        sw.WriteLine("// ── Nodes ────────────────────────────────────────────────────────");

        foreach (var node in graph.Nodes.Values)
        {
            var props = BuildProps(new Dictionary<string, string>(node.Meta)
            {
                ["id"]           = node.Id,
                ["label"]        = node.Label,
                ["isEntryPoint"] = node.IsEntryPoint ? "true" : "false"
            });
            sw.WriteLine($"MERGE (n:Node:{EscapeLabel(node.Kind.ToString())} {{ id: {Q(node.Id)} }}) SET n += {props};");
        }

        sw.WriteLine();
        sw.WriteLine("// ── Edges ────────────────────────────────────────────────────────");

        foreach (var edge in graph.Edges)
        {
            var relType = edge.Kind.ToString().ToUpperInvariant();
            var metaProps = edge.Meta.Count > 0 ? $" {{ {string.Join(", ", edge.Meta.Select(kv => $"{kv.Key}: {Q(kv.Value)}"))} }}" : "";
            sw.WriteLine(
                $"MATCH (s:Node {{ id: {Q(edge.SourceId)} }}), (t:Node {{ id: {Q(edge.TargetId)} }}) " +
                $"MERGE (s)-[:{relType}{metaProps}]->(t);");
        }

        Console.WriteLine($"  Cypher → {outputPath}");
        return Task.CompletedTask;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string Q(string s) =>
        "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string EscapeLabel(string s) =>
        string.Concat(s.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c.ToString() : "_"));

    private static string BuildProps(Dictionary<string, string> props)
    {
        var pairs = props.Select(kv => $"{kv.Key}: {Q(kv.Value)}");
        return "{ " + string.Join(", ", pairs) + " }";
    }
}
